---
- name: Setup Vprofile Bastion Host
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Import Bastion Variables
      include_vars: vars/bastion_setup

    - name: Import VPCID Output Variables
      include_vars: vars/output_vars

    - name: Create vprofile ec2 key
      ec2_key:
        name: vprofile-key
        region: us-east-2
      register: key_out

    - name: Save Private Key into File bastion-key.pem
      copy:
        content: "{{key_out.key.private_key}}"
        dest: "./bastion-key.pem"
        mode: 0600
      when: key_out.changed

    - name: Create Sec grp for bastion host
      ec2_group:
        name: Bastion-host-sg
        description: Allow port 22 from everywhere and all port within sg
        region: "{{region}}"
        vpc_id: "{{vpcid}}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: "{{MYIP}}"
      register: BastionSG_out

    - name: Creating Bastion Host
      ec2:
        key_name: vprofile-key
        region: "{{region}}"
        instance_type: t2.micro
        image: "{{bastion_ami}}"
        wait: yes
        wait_timeout: 300
    #    instance_tags:
    #      Name: Bastion_host
    #     count_tag:
    #      Name: Bastion_host
    #    exact_count: 1
        vpc_subnet_id: "{{pubsub1id}}"
    #   group_id: "{{BastionSG_out.group_id}}"
      register: bastionHost_out




